// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cartographer/transform/proto/timestamped_transform.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_cartographer_2ftransform_2fproto_2ftimestamped_5ftransform_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_cartographer_2ftransform_2fproto_2ftimestamped_5ftransform_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3011000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3011002 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "cartographer/transform/proto/transform.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_cartographer_2ftransform_2fproto_2ftimestamped_5ftransform_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_cartographer_2ftransform_2fproto_2ftimestamped_5ftransform_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[1]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_cartographer_2ftransform_2fproto_2ftimestamped_5ftransform_2eproto;
namespace cartographer {
namespace transform {
namespace proto {
class TimestampedTransform;
class TimestampedTransformDefaultTypeInternal;
extern TimestampedTransformDefaultTypeInternal _TimestampedTransform_default_instance_;
}  // namespace proto
}  // namespace transform
}  // namespace cartographer
PROTOBUF_NAMESPACE_OPEN
template<> ::cartographer::transform::proto::TimestampedTransform* Arena::CreateMaybeMessage<::cartographer::transform::proto::TimestampedTransform>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace cartographer {
namespace transform {
namespace proto {

// ===================================================================

class TimestampedTransform :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:cartographer.transform.proto.TimestampedTransform) */ {
 public:
  TimestampedTransform();
  virtual ~TimestampedTransform();

  TimestampedTransform(const TimestampedTransform& from);
  TimestampedTransform(TimestampedTransform&& from) noexcept
    : TimestampedTransform() {
    *this = ::std::move(from);
  }

  inline TimestampedTransform& operator=(const TimestampedTransform& from) {
    CopyFrom(from);
    return *this;
  }
  inline TimestampedTransform& operator=(TimestampedTransform&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const TimestampedTransform& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const TimestampedTransform* internal_default_instance() {
    return reinterpret_cast<const TimestampedTransform*>(
               &_TimestampedTransform_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(TimestampedTransform& a, TimestampedTransform& b) {
    a.Swap(&b);
  }
  inline void Swap(TimestampedTransform* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline TimestampedTransform* New() const final {
    return CreateMaybeMessage<TimestampedTransform>(nullptr);
  }

  TimestampedTransform* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<TimestampedTransform>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const TimestampedTransform& from);
  void MergeFrom(const TimestampedTransform& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(TimestampedTransform* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "cartographer.transform.proto.TimestampedTransform";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_cartographer_2ftransform_2fproto_2ftimestamped_5ftransform_2eproto);
    return ::descriptor_table_cartographer_2ftransform_2fproto_2ftimestamped_5ftransform_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kTransformFieldNumber = 2,
    kTimeFieldNumber = 1,
  };
  // .cartographer.transform.proto.Rigid3d transform = 2;
  bool has_transform() const;
  private:
  bool _internal_has_transform() const;
  public:
  void clear_transform();
  const ::cartographer::transform::proto::Rigid3d& transform() const;
  ::cartographer::transform::proto::Rigid3d* release_transform();
  ::cartographer::transform::proto::Rigid3d* mutable_transform();
  void set_allocated_transform(::cartographer::transform::proto::Rigid3d* transform);
  private:
  const ::cartographer::transform::proto::Rigid3d& _internal_transform() const;
  ::cartographer::transform::proto::Rigid3d* _internal_mutable_transform();
  public:

  // int64 time = 1;
  void clear_time();
  ::PROTOBUF_NAMESPACE_ID::int64 time() const;
  void set_time(::PROTOBUF_NAMESPACE_ID::int64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int64 _internal_time() const;
  void _internal_set_time(::PROTOBUF_NAMESPACE_ID::int64 value);
  public:

  // @@protoc_insertion_point(class_scope:cartographer.transform.proto.TimestampedTransform)
 private:
  class _Internal;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::cartographer::transform::proto::Rigid3d* transform_;
  ::PROTOBUF_NAMESPACE_ID::int64 time_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_cartographer_2ftransform_2fproto_2ftimestamped_5ftransform_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// TimestampedTransform

// int64 time = 1;
inline void TimestampedTransform::clear_time() {
  time_ = PROTOBUF_LONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::int64 TimestampedTransform::_internal_time() const {
  return time_;
}
inline ::PROTOBUF_NAMESPACE_ID::int64 TimestampedTransform::time() const {
  // @@protoc_insertion_point(field_get:cartographer.transform.proto.TimestampedTransform.time)
  return _internal_time();
}
inline void TimestampedTransform::_internal_set_time(::PROTOBUF_NAMESPACE_ID::int64 value) {
  
  time_ = value;
}
inline void TimestampedTransform::set_time(::PROTOBUF_NAMESPACE_ID::int64 value) {
  _internal_set_time(value);
  // @@protoc_insertion_point(field_set:cartographer.transform.proto.TimestampedTransform.time)
}

// .cartographer.transform.proto.Rigid3d transform = 2;
inline bool TimestampedTransform::_internal_has_transform() const {
  return this != internal_default_instance() && transform_ != nullptr;
}
inline bool TimestampedTransform::has_transform() const {
  return _internal_has_transform();
}
inline const ::cartographer::transform::proto::Rigid3d& TimestampedTransform::_internal_transform() const {
  const ::cartographer::transform::proto::Rigid3d* p = transform_;
  return p != nullptr ? *p : *reinterpret_cast<const ::cartographer::transform::proto::Rigid3d*>(
      &::cartographer::transform::proto::_Rigid3d_default_instance_);
}
inline const ::cartographer::transform::proto::Rigid3d& TimestampedTransform::transform() const {
  // @@protoc_insertion_point(field_get:cartographer.transform.proto.TimestampedTransform.transform)
  return _internal_transform();
}
inline ::cartographer::transform::proto::Rigid3d* TimestampedTransform::release_transform() {
  // @@protoc_insertion_point(field_release:cartographer.transform.proto.TimestampedTransform.transform)
  
  ::cartographer::transform::proto::Rigid3d* temp = transform_;
  transform_ = nullptr;
  return temp;
}
inline ::cartographer::transform::proto::Rigid3d* TimestampedTransform::_internal_mutable_transform() {
  
  if (transform_ == nullptr) {
    auto* p = CreateMaybeMessage<::cartographer::transform::proto::Rigid3d>(GetArenaNoVirtual());
    transform_ = p;
  }
  return transform_;
}
inline ::cartographer::transform::proto::Rigid3d* TimestampedTransform::mutable_transform() {
  // @@protoc_insertion_point(field_mutable:cartographer.transform.proto.TimestampedTransform.transform)
  return _internal_mutable_transform();
}
inline void TimestampedTransform::set_allocated_transform(::cartographer::transform::proto::Rigid3d* transform) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(transform_);
  }
  if (transform) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena = nullptr;
    if (message_arena != submessage_arena) {
      transform = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, transform, submessage_arena);
    }
    
  } else {
    
  }
  transform_ = transform;
  // @@protoc_insertion_point(field_set_allocated:cartographer.transform.proto.TimestampedTransform.transform)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace proto
}  // namespace transform
}  // namespace cartographer

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_cartographer_2ftransform_2fproto_2ftimestamped_5ftransform_2eproto
