// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cartographer/transform/proto/transform.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_cartographer_2ftransform_2fproto_2ftransform_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_cartographer_2ftransform_2fproto_2ftransform_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3011000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3011002 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_cartographer_2ftransform_2fproto_2ftransform_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_cartographer_2ftransform_2fproto_2ftransform_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[11]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_cartographer_2ftransform_2fproto_2ftransform_2eproto;
namespace cartographer {
namespace transform {
namespace proto {
class Quaterniond;
class QuaterniondDefaultTypeInternal;
extern QuaterniondDefaultTypeInternal _Quaterniond_default_instance_;
class Quaternionf;
class QuaternionfDefaultTypeInternal;
extern QuaternionfDefaultTypeInternal _Quaternionf_default_instance_;
class Rigid2d;
class Rigid2dDefaultTypeInternal;
extern Rigid2dDefaultTypeInternal _Rigid2d_default_instance_;
class Rigid2f;
class Rigid2fDefaultTypeInternal;
extern Rigid2fDefaultTypeInternal _Rigid2f_default_instance_;
class Rigid3d;
class Rigid3dDefaultTypeInternal;
extern Rigid3dDefaultTypeInternal _Rigid3d_default_instance_;
class Rigid3f;
class Rigid3fDefaultTypeInternal;
extern Rigid3fDefaultTypeInternal _Rigid3f_default_instance_;
class Vector2d;
class Vector2dDefaultTypeInternal;
extern Vector2dDefaultTypeInternal _Vector2d_default_instance_;
class Vector2f;
class Vector2fDefaultTypeInternal;
extern Vector2fDefaultTypeInternal _Vector2f_default_instance_;
class Vector3d;
class Vector3dDefaultTypeInternal;
extern Vector3dDefaultTypeInternal _Vector3d_default_instance_;
class Vector3f;
class Vector3fDefaultTypeInternal;
extern Vector3fDefaultTypeInternal _Vector3f_default_instance_;
class Vector4f;
class Vector4fDefaultTypeInternal;
extern Vector4fDefaultTypeInternal _Vector4f_default_instance_;
}  // namespace proto
}  // namespace transform
}  // namespace cartographer
PROTOBUF_NAMESPACE_OPEN
template<> ::cartographer::transform::proto::Quaterniond* Arena::CreateMaybeMessage<::cartographer::transform::proto::Quaterniond>(Arena*);
template<> ::cartographer::transform::proto::Quaternionf* Arena::CreateMaybeMessage<::cartographer::transform::proto::Quaternionf>(Arena*);
template<> ::cartographer::transform::proto::Rigid2d* Arena::CreateMaybeMessage<::cartographer::transform::proto::Rigid2d>(Arena*);
template<> ::cartographer::transform::proto::Rigid2f* Arena::CreateMaybeMessage<::cartographer::transform::proto::Rigid2f>(Arena*);
template<> ::cartographer::transform::proto::Rigid3d* Arena::CreateMaybeMessage<::cartographer::transform::proto::Rigid3d>(Arena*);
template<> ::cartographer::transform::proto::Rigid3f* Arena::CreateMaybeMessage<::cartographer::transform::proto::Rigid3f>(Arena*);
template<> ::cartographer::transform::proto::Vector2d* Arena::CreateMaybeMessage<::cartographer::transform::proto::Vector2d>(Arena*);
template<> ::cartographer::transform::proto::Vector2f* Arena::CreateMaybeMessage<::cartographer::transform::proto::Vector2f>(Arena*);
template<> ::cartographer::transform::proto::Vector3d* Arena::CreateMaybeMessage<::cartographer::transform::proto::Vector3d>(Arena*);
template<> ::cartographer::transform::proto::Vector3f* Arena::CreateMaybeMessage<::cartographer::transform::proto::Vector3f>(Arena*);
template<> ::cartographer::transform::proto::Vector4f* Arena::CreateMaybeMessage<::cartographer::transform::proto::Vector4f>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace cartographer {
namespace transform {
namespace proto {

// ===================================================================

class Vector2d :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:cartographer.transform.proto.Vector2d) */ {
 public:
  Vector2d();
  virtual ~Vector2d();

  Vector2d(const Vector2d& from);
  Vector2d(Vector2d&& from) noexcept
    : Vector2d() {
    *this = ::std::move(from);
  }

  inline Vector2d& operator=(const Vector2d& from) {
    CopyFrom(from);
    return *this;
  }
  inline Vector2d& operator=(Vector2d&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const Vector2d& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Vector2d* internal_default_instance() {
    return reinterpret_cast<const Vector2d*>(
               &_Vector2d_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(Vector2d& a, Vector2d& b) {
    a.Swap(&b);
  }
  inline void Swap(Vector2d* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline Vector2d* New() const final {
    return CreateMaybeMessage<Vector2d>(nullptr);
  }

  Vector2d* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<Vector2d>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const Vector2d& from);
  void MergeFrom(const Vector2d& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Vector2d* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "cartographer.transform.proto.Vector2d";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_cartographer_2ftransform_2fproto_2ftransform_2eproto);
    return ::descriptor_table_cartographer_2ftransform_2fproto_2ftransform_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kXFieldNumber = 1,
    kYFieldNumber = 2,
  };
  // double x = 1;
  void clear_x();
  double x() const;
  void set_x(double value);
  private:
  double _internal_x() const;
  void _internal_set_x(double value);
  public:

  // double y = 2;
  void clear_y();
  double y() const;
  void set_y(double value);
  private:
  double _internal_y() const;
  void _internal_set_y(double value);
  public:

  // @@protoc_insertion_point(class_scope:cartographer.transform.proto.Vector2d)
 private:
  class _Internal;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  double x_;
  double y_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_cartographer_2ftransform_2fproto_2ftransform_2eproto;
};
// -------------------------------------------------------------------

class Vector2f :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:cartographer.transform.proto.Vector2f) */ {
 public:
  Vector2f();
  virtual ~Vector2f();

  Vector2f(const Vector2f& from);
  Vector2f(Vector2f&& from) noexcept
    : Vector2f() {
    *this = ::std::move(from);
  }

  inline Vector2f& operator=(const Vector2f& from) {
    CopyFrom(from);
    return *this;
  }
  inline Vector2f& operator=(Vector2f&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const Vector2f& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Vector2f* internal_default_instance() {
    return reinterpret_cast<const Vector2f*>(
               &_Vector2f_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(Vector2f& a, Vector2f& b) {
    a.Swap(&b);
  }
  inline void Swap(Vector2f* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline Vector2f* New() const final {
    return CreateMaybeMessage<Vector2f>(nullptr);
  }

  Vector2f* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<Vector2f>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const Vector2f& from);
  void MergeFrom(const Vector2f& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Vector2f* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "cartographer.transform.proto.Vector2f";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_cartographer_2ftransform_2fproto_2ftransform_2eproto);
    return ::descriptor_table_cartographer_2ftransform_2fproto_2ftransform_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kXFieldNumber = 1,
    kYFieldNumber = 2,
  };
  // float x = 1;
  void clear_x();
  float x() const;
  void set_x(float value);
  private:
  float _internal_x() const;
  void _internal_set_x(float value);
  public:

  // float y = 2;
  void clear_y();
  float y() const;
  void set_y(float value);
  private:
  float _internal_y() const;
  void _internal_set_y(float value);
  public:

  // @@protoc_insertion_point(class_scope:cartographer.transform.proto.Vector2f)
 private:
  class _Internal;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  float x_;
  float y_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_cartographer_2ftransform_2fproto_2ftransform_2eproto;
};
// -------------------------------------------------------------------

class Vector3d :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:cartographer.transform.proto.Vector3d) */ {
 public:
  Vector3d();
  virtual ~Vector3d();

  Vector3d(const Vector3d& from);
  Vector3d(Vector3d&& from) noexcept
    : Vector3d() {
    *this = ::std::move(from);
  }

  inline Vector3d& operator=(const Vector3d& from) {
    CopyFrom(from);
    return *this;
  }
  inline Vector3d& operator=(Vector3d&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const Vector3d& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Vector3d* internal_default_instance() {
    return reinterpret_cast<const Vector3d*>(
               &_Vector3d_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(Vector3d& a, Vector3d& b) {
    a.Swap(&b);
  }
  inline void Swap(Vector3d* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline Vector3d* New() const final {
    return CreateMaybeMessage<Vector3d>(nullptr);
  }

  Vector3d* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<Vector3d>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const Vector3d& from);
  void MergeFrom(const Vector3d& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Vector3d* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "cartographer.transform.proto.Vector3d";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_cartographer_2ftransform_2fproto_2ftransform_2eproto);
    return ::descriptor_table_cartographer_2ftransform_2fproto_2ftransform_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kXFieldNumber = 1,
    kYFieldNumber = 2,
    kZFieldNumber = 3,
  };
  // double x = 1;
  void clear_x();
  double x() const;
  void set_x(double value);
  private:
  double _internal_x() const;
  void _internal_set_x(double value);
  public:

  // double y = 2;
  void clear_y();
  double y() const;
  void set_y(double value);
  private:
  double _internal_y() const;
  void _internal_set_y(double value);
  public:

  // double z = 3;
  void clear_z();
  double z() const;
  void set_z(double value);
  private:
  double _internal_z() const;
  void _internal_set_z(double value);
  public:

  // @@protoc_insertion_point(class_scope:cartographer.transform.proto.Vector3d)
 private:
  class _Internal;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  double x_;
  double y_;
  double z_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_cartographer_2ftransform_2fproto_2ftransform_2eproto;
};
// -------------------------------------------------------------------

class Vector3f :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:cartographer.transform.proto.Vector3f) */ {
 public:
  Vector3f();
  virtual ~Vector3f();

  Vector3f(const Vector3f& from);
  Vector3f(Vector3f&& from) noexcept
    : Vector3f() {
    *this = ::std::move(from);
  }

  inline Vector3f& operator=(const Vector3f& from) {
    CopyFrom(from);
    return *this;
  }
  inline Vector3f& operator=(Vector3f&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const Vector3f& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Vector3f* internal_default_instance() {
    return reinterpret_cast<const Vector3f*>(
               &_Vector3f_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(Vector3f& a, Vector3f& b) {
    a.Swap(&b);
  }
  inline void Swap(Vector3f* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline Vector3f* New() const final {
    return CreateMaybeMessage<Vector3f>(nullptr);
  }

  Vector3f* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<Vector3f>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const Vector3f& from);
  void MergeFrom(const Vector3f& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Vector3f* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "cartographer.transform.proto.Vector3f";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_cartographer_2ftransform_2fproto_2ftransform_2eproto);
    return ::descriptor_table_cartographer_2ftransform_2fproto_2ftransform_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kXFieldNumber = 1,
    kYFieldNumber = 2,
    kZFieldNumber = 3,
  };
  // float x = 1;
  void clear_x();
  float x() const;
  void set_x(float value);
  private:
  float _internal_x() const;
  void _internal_set_x(float value);
  public:

  // float y = 2;
  void clear_y();
  float y() const;
  void set_y(float value);
  private:
  float _internal_y() const;
  void _internal_set_y(float value);
  public:

  // float z = 3;
  void clear_z();
  float z() const;
  void set_z(float value);
  private:
  float _internal_z() const;
  void _internal_set_z(float value);
  public:

  // @@protoc_insertion_point(class_scope:cartographer.transform.proto.Vector3f)
 private:
  class _Internal;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  float x_;
  float y_;
  float z_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_cartographer_2ftransform_2fproto_2ftransform_2eproto;
};
// -------------------------------------------------------------------

class Vector4f :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:cartographer.transform.proto.Vector4f) */ {
 public:
  Vector4f();
  virtual ~Vector4f();

  Vector4f(const Vector4f& from);
  Vector4f(Vector4f&& from) noexcept
    : Vector4f() {
    *this = ::std::move(from);
  }

  inline Vector4f& operator=(const Vector4f& from) {
    CopyFrom(from);
    return *this;
  }
  inline Vector4f& operator=(Vector4f&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const Vector4f& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Vector4f* internal_default_instance() {
    return reinterpret_cast<const Vector4f*>(
               &_Vector4f_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  friend void swap(Vector4f& a, Vector4f& b) {
    a.Swap(&b);
  }
  inline void Swap(Vector4f* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline Vector4f* New() const final {
    return CreateMaybeMessage<Vector4f>(nullptr);
  }

  Vector4f* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<Vector4f>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const Vector4f& from);
  void MergeFrom(const Vector4f& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Vector4f* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "cartographer.transform.proto.Vector4f";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_cartographer_2ftransform_2fproto_2ftransform_2eproto);
    return ::descriptor_table_cartographer_2ftransform_2fproto_2ftransform_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kXFieldNumber = 1,
    kYFieldNumber = 2,
    kZFieldNumber = 3,
    kTFieldNumber = 4,
  };
  // float x = 1;
  void clear_x();
  float x() const;
  void set_x(float value);
  private:
  float _internal_x() const;
  void _internal_set_x(float value);
  public:

  // float y = 2;
  void clear_y();
  float y() const;
  void set_y(float value);
  private:
  float _internal_y() const;
  void _internal_set_y(float value);
  public:

  // float z = 3;
  void clear_z();
  float z() const;
  void set_z(float value);
  private:
  float _internal_z() const;
  void _internal_set_z(float value);
  public:

  // float t = 4;
  void clear_t();
  float t() const;
  void set_t(float value);
  private:
  float _internal_t() const;
  void _internal_set_t(float value);
  public:

  // @@protoc_insertion_point(class_scope:cartographer.transform.proto.Vector4f)
 private:
  class _Internal;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  float x_;
  float y_;
  float z_;
  float t_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_cartographer_2ftransform_2fproto_2ftransform_2eproto;
};
// -------------------------------------------------------------------

class Quaterniond :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:cartographer.transform.proto.Quaterniond) */ {
 public:
  Quaterniond();
  virtual ~Quaterniond();

  Quaterniond(const Quaterniond& from);
  Quaterniond(Quaterniond&& from) noexcept
    : Quaterniond() {
    *this = ::std::move(from);
  }

  inline Quaterniond& operator=(const Quaterniond& from) {
    CopyFrom(from);
    return *this;
  }
  inline Quaterniond& operator=(Quaterniond&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const Quaterniond& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Quaterniond* internal_default_instance() {
    return reinterpret_cast<const Quaterniond*>(
               &_Quaterniond_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    5;

  friend void swap(Quaterniond& a, Quaterniond& b) {
    a.Swap(&b);
  }
  inline void Swap(Quaterniond* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline Quaterniond* New() const final {
    return CreateMaybeMessage<Quaterniond>(nullptr);
  }

  Quaterniond* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<Quaterniond>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const Quaterniond& from);
  void MergeFrom(const Quaterniond& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Quaterniond* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "cartographer.transform.proto.Quaterniond";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_cartographer_2ftransform_2fproto_2ftransform_2eproto);
    return ::descriptor_table_cartographer_2ftransform_2fproto_2ftransform_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kXFieldNumber = 1,
    kYFieldNumber = 2,
    kZFieldNumber = 3,
    kWFieldNumber = 4,
  };
  // double x = 1;
  void clear_x();
  double x() const;
  void set_x(double value);
  private:
  double _internal_x() const;
  void _internal_set_x(double value);
  public:

  // double y = 2;
  void clear_y();
  double y() const;
  void set_y(double value);
  private:
  double _internal_y() const;
  void _internal_set_y(double value);
  public:

  // double z = 3;
  void clear_z();
  double z() const;
  void set_z(double value);
  private:
  double _internal_z() const;
  void _internal_set_z(double value);
  public:

  // double w = 4;
  void clear_w();
  double w() const;
  void set_w(double value);
  private:
  double _internal_w() const;
  void _internal_set_w(double value);
  public:

  // @@protoc_insertion_point(class_scope:cartographer.transform.proto.Quaterniond)
 private:
  class _Internal;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  double x_;
  double y_;
  double z_;
  double w_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_cartographer_2ftransform_2fproto_2ftransform_2eproto;
};
// -------------------------------------------------------------------

class Quaternionf :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:cartographer.transform.proto.Quaternionf) */ {
 public:
  Quaternionf();
  virtual ~Quaternionf();

  Quaternionf(const Quaternionf& from);
  Quaternionf(Quaternionf&& from) noexcept
    : Quaternionf() {
    *this = ::std::move(from);
  }

  inline Quaternionf& operator=(const Quaternionf& from) {
    CopyFrom(from);
    return *this;
  }
  inline Quaternionf& operator=(Quaternionf&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const Quaternionf& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Quaternionf* internal_default_instance() {
    return reinterpret_cast<const Quaternionf*>(
               &_Quaternionf_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    6;

  friend void swap(Quaternionf& a, Quaternionf& b) {
    a.Swap(&b);
  }
  inline void Swap(Quaternionf* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline Quaternionf* New() const final {
    return CreateMaybeMessage<Quaternionf>(nullptr);
  }

  Quaternionf* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<Quaternionf>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const Quaternionf& from);
  void MergeFrom(const Quaternionf& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Quaternionf* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "cartographer.transform.proto.Quaternionf";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_cartographer_2ftransform_2fproto_2ftransform_2eproto);
    return ::descriptor_table_cartographer_2ftransform_2fproto_2ftransform_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kXFieldNumber = 1,
    kYFieldNumber = 2,
    kZFieldNumber = 3,
    kWFieldNumber = 4,
  };
  // float x = 1;
  void clear_x();
  float x() const;
  void set_x(float value);
  private:
  float _internal_x() const;
  void _internal_set_x(float value);
  public:

  // float y = 2;
  void clear_y();
  float y() const;
  void set_y(float value);
  private:
  float _internal_y() const;
  void _internal_set_y(float value);
  public:

  // float z = 3;
  void clear_z();
  float z() const;
  void set_z(float value);
  private:
  float _internal_z() const;
  void _internal_set_z(float value);
  public:

  // float w = 4;
  void clear_w();
  float w() const;
  void set_w(float value);
  private:
  float _internal_w() const;
  void _internal_set_w(float value);
  public:

  // @@protoc_insertion_point(class_scope:cartographer.transform.proto.Quaternionf)
 private:
  class _Internal;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  float x_;
  float y_;
  float z_;
  float w_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_cartographer_2ftransform_2fproto_2ftransform_2eproto;
};
// -------------------------------------------------------------------

class Rigid2d :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:cartographer.transform.proto.Rigid2d) */ {
 public:
  Rigid2d();
  virtual ~Rigid2d();

  Rigid2d(const Rigid2d& from);
  Rigid2d(Rigid2d&& from) noexcept
    : Rigid2d() {
    *this = ::std::move(from);
  }

  inline Rigid2d& operator=(const Rigid2d& from) {
    CopyFrom(from);
    return *this;
  }
  inline Rigid2d& operator=(Rigid2d&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const Rigid2d& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Rigid2d* internal_default_instance() {
    return reinterpret_cast<const Rigid2d*>(
               &_Rigid2d_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    7;

  friend void swap(Rigid2d& a, Rigid2d& b) {
    a.Swap(&b);
  }
  inline void Swap(Rigid2d* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline Rigid2d* New() const final {
    return CreateMaybeMessage<Rigid2d>(nullptr);
  }

  Rigid2d* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<Rigid2d>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const Rigid2d& from);
  void MergeFrom(const Rigid2d& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Rigid2d* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "cartographer.transform.proto.Rigid2d";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_cartographer_2ftransform_2fproto_2ftransform_2eproto);
    return ::descriptor_table_cartographer_2ftransform_2fproto_2ftransform_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kTranslationFieldNumber = 1,
    kRotationFieldNumber = 2,
  };
  // .cartographer.transform.proto.Vector2d translation = 1;
  bool has_translation() const;
  private:
  bool _internal_has_translation() const;
  public:
  void clear_translation();
  const ::cartographer::transform::proto::Vector2d& translation() const;
  ::cartographer::transform::proto::Vector2d* release_translation();
  ::cartographer::transform::proto::Vector2d* mutable_translation();
  void set_allocated_translation(::cartographer::transform::proto::Vector2d* translation);
  private:
  const ::cartographer::transform::proto::Vector2d& _internal_translation() const;
  ::cartographer::transform::proto::Vector2d* _internal_mutable_translation();
  public:

  // double rotation = 2;
  void clear_rotation();
  double rotation() const;
  void set_rotation(double value);
  private:
  double _internal_rotation() const;
  void _internal_set_rotation(double value);
  public:

  // @@protoc_insertion_point(class_scope:cartographer.transform.proto.Rigid2d)
 private:
  class _Internal;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::cartographer::transform::proto::Vector2d* translation_;
  double rotation_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_cartographer_2ftransform_2fproto_2ftransform_2eproto;
};
// -------------------------------------------------------------------

class Rigid2f :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:cartographer.transform.proto.Rigid2f) */ {
 public:
  Rigid2f();
  virtual ~Rigid2f();

  Rigid2f(const Rigid2f& from);
  Rigid2f(Rigid2f&& from) noexcept
    : Rigid2f() {
    *this = ::std::move(from);
  }

  inline Rigid2f& operator=(const Rigid2f& from) {
    CopyFrom(from);
    return *this;
  }
  inline Rigid2f& operator=(Rigid2f&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const Rigid2f& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Rigid2f* internal_default_instance() {
    return reinterpret_cast<const Rigid2f*>(
               &_Rigid2f_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    8;

  friend void swap(Rigid2f& a, Rigid2f& b) {
    a.Swap(&b);
  }
  inline void Swap(Rigid2f* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline Rigid2f* New() const final {
    return CreateMaybeMessage<Rigid2f>(nullptr);
  }

  Rigid2f* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<Rigid2f>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const Rigid2f& from);
  void MergeFrom(const Rigid2f& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Rigid2f* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "cartographer.transform.proto.Rigid2f";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_cartographer_2ftransform_2fproto_2ftransform_2eproto);
    return ::descriptor_table_cartographer_2ftransform_2fproto_2ftransform_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kTranslationFieldNumber = 1,
    kRotationFieldNumber = 2,
  };
  // .cartographer.transform.proto.Vector2f translation = 1;
  bool has_translation() const;
  private:
  bool _internal_has_translation() const;
  public:
  void clear_translation();
  const ::cartographer::transform::proto::Vector2f& translation() const;
  ::cartographer::transform::proto::Vector2f* release_translation();
  ::cartographer::transform::proto::Vector2f* mutable_translation();
  void set_allocated_translation(::cartographer::transform::proto::Vector2f* translation);
  private:
  const ::cartographer::transform::proto::Vector2f& _internal_translation() const;
  ::cartographer::transform::proto::Vector2f* _internal_mutable_translation();
  public:

  // float rotation = 2;
  void clear_rotation();
  float rotation() const;
  void set_rotation(float value);
  private:
  float _internal_rotation() const;
  void _internal_set_rotation(float value);
  public:

  // @@protoc_insertion_point(class_scope:cartographer.transform.proto.Rigid2f)
 private:
  class _Internal;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::cartographer::transform::proto::Vector2f* translation_;
  float rotation_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_cartographer_2ftransform_2fproto_2ftransform_2eproto;
};
// -------------------------------------------------------------------

class Rigid3d :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:cartographer.transform.proto.Rigid3d) */ {
 public:
  Rigid3d();
  virtual ~Rigid3d();

  Rigid3d(const Rigid3d& from);
  Rigid3d(Rigid3d&& from) noexcept
    : Rigid3d() {
    *this = ::std::move(from);
  }

  inline Rigid3d& operator=(const Rigid3d& from) {
    CopyFrom(from);
    return *this;
  }
  inline Rigid3d& operator=(Rigid3d&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const Rigid3d& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Rigid3d* internal_default_instance() {
    return reinterpret_cast<const Rigid3d*>(
               &_Rigid3d_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    9;

  friend void swap(Rigid3d& a, Rigid3d& b) {
    a.Swap(&b);
  }
  inline void Swap(Rigid3d* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline Rigid3d* New() const final {
    return CreateMaybeMessage<Rigid3d>(nullptr);
  }

  Rigid3d* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<Rigid3d>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const Rigid3d& from);
  void MergeFrom(const Rigid3d& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Rigid3d* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "cartographer.transform.proto.Rigid3d";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_cartographer_2ftransform_2fproto_2ftransform_2eproto);
    return ::descriptor_table_cartographer_2ftransform_2fproto_2ftransform_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kTranslationFieldNumber = 1,
    kRotationFieldNumber = 2,
  };
  // .cartographer.transform.proto.Vector3d translation = 1;
  bool has_translation() const;
  private:
  bool _internal_has_translation() const;
  public:
  void clear_translation();
  const ::cartographer::transform::proto::Vector3d& translation() const;
  ::cartographer::transform::proto::Vector3d* release_translation();
  ::cartographer::transform::proto::Vector3d* mutable_translation();
  void set_allocated_translation(::cartographer::transform::proto::Vector3d* translation);
  private:
  const ::cartographer::transform::proto::Vector3d& _internal_translation() const;
  ::cartographer::transform::proto::Vector3d* _internal_mutable_translation();
  public:

  // .cartographer.transform.proto.Quaterniond rotation = 2;
  bool has_rotation() const;
  private:
  bool _internal_has_rotation() const;
  public:
  void clear_rotation();
  const ::cartographer::transform::proto::Quaterniond& rotation() const;
  ::cartographer::transform::proto::Quaterniond* release_rotation();
  ::cartographer::transform::proto::Quaterniond* mutable_rotation();
  void set_allocated_rotation(::cartographer::transform::proto::Quaterniond* rotation);
  private:
  const ::cartographer::transform::proto::Quaterniond& _internal_rotation() const;
  ::cartographer::transform::proto::Quaterniond* _internal_mutable_rotation();
  public:

  // @@protoc_insertion_point(class_scope:cartographer.transform.proto.Rigid3d)
 private:
  class _Internal;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::cartographer::transform::proto::Vector3d* translation_;
  ::cartographer::transform::proto::Quaterniond* rotation_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_cartographer_2ftransform_2fproto_2ftransform_2eproto;
};
// -------------------------------------------------------------------

class Rigid3f :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:cartographer.transform.proto.Rigid3f) */ {
 public:
  Rigid3f();
  virtual ~Rigid3f();

  Rigid3f(const Rigid3f& from);
  Rigid3f(Rigid3f&& from) noexcept
    : Rigid3f() {
    *this = ::std::move(from);
  }

  inline Rigid3f& operator=(const Rigid3f& from) {
    CopyFrom(from);
    return *this;
  }
  inline Rigid3f& operator=(Rigid3f&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const Rigid3f& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Rigid3f* internal_default_instance() {
    return reinterpret_cast<const Rigid3f*>(
               &_Rigid3f_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    10;

  friend void swap(Rigid3f& a, Rigid3f& b) {
    a.Swap(&b);
  }
  inline void Swap(Rigid3f* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline Rigid3f* New() const final {
    return CreateMaybeMessage<Rigid3f>(nullptr);
  }

  Rigid3f* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<Rigid3f>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const Rigid3f& from);
  void MergeFrom(const Rigid3f& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Rigid3f* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "cartographer.transform.proto.Rigid3f";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_cartographer_2ftransform_2fproto_2ftransform_2eproto);
    return ::descriptor_table_cartographer_2ftransform_2fproto_2ftransform_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kTranslationFieldNumber = 1,
    kRotationFieldNumber = 2,
  };
  // .cartographer.transform.proto.Vector3f translation = 1;
  bool has_translation() const;
  private:
  bool _internal_has_translation() const;
  public:
  void clear_translation();
  const ::cartographer::transform::proto::Vector3f& translation() const;
  ::cartographer::transform::proto::Vector3f* release_translation();
  ::cartographer::transform::proto::Vector3f* mutable_translation();
  void set_allocated_translation(::cartographer::transform::proto::Vector3f* translation);
  private:
  const ::cartographer::transform::proto::Vector3f& _internal_translation() const;
  ::cartographer::transform::proto::Vector3f* _internal_mutable_translation();
  public:

  // .cartographer.transform.proto.Quaternionf rotation = 2;
  bool has_rotation() const;
  private:
  bool _internal_has_rotation() const;
  public:
  void clear_rotation();
  const ::cartographer::transform::proto::Quaternionf& rotation() const;
  ::cartographer::transform::proto::Quaternionf* release_rotation();
  ::cartographer::transform::proto::Quaternionf* mutable_rotation();
  void set_allocated_rotation(::cartographer::transform::proto::Quaternionf* rotation);
  private:
  const ::cartographer::transform::proto::Quaternionf& _internal_rotation() const;
  ::cartographer::transform::proto::Quaternionf* _internal_mutable_rotation();
  public:

  // @@protoc_insertion_point(class_scope:cartographer.transform.proto.Rigid3f)
 private:
  class _Internal;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::cartographer::transform::proto::Vector3f* translation_;
  ::cartographer::transform::proto::Quaternionf* rotation_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_cartographer_2ftransform_2fproto_2ftransform_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// Vector2d

// double x = 1;
inline void Vector2d::clear_x() {
  x_ = 0;
}
inline double Vector2d::_internal_x() const {
  return x_;
}
inline double Vector2d::x() const {
  // @@protoc_insertion_point(field_get:cartographer.transform.proto.Vector2d.x)
  return _internal_x();
}
inline void Vector2d::_internal_set_x(double value) {
  
  x_ = value;
}
inline void Vector2d::set_x(double value) {
  _internal_set_x(value);
  // @@protoc_insertion_point(field_set:cartographer.transform.proto.Vector2d.x)
}

// double y = 2;
inline void Vector2d::clear_y() {
  y_ = 0;
}
inline double Vector2d::_internal_y() const {
  return y_;
}
inline double Vector2d::y() const {
  // @@protoc_insertion_point(field_get:cartographer.transform.proto.Vector2d.y)
  return _internal_y();
}
inline void Vector2d::_internal_set_y(double value) {
  
  y_ = value;
}
inline void Vector2d::set_y(double value) {
  _internal_set_y(value);
  // @@protoc_insertion_point(field_set:cartographer.transform.proto.Vector2d.y)
}

// -------------------------------------------------------------------

// Vector2f

// float x = 1;
inline void Vector2f::clear_x() {
  x_ = 0;
}
inline float Vector2f::_internal_x() const {
  return x_;
}
inline float Vector2f::x() const {
  // @@protoc_insertion_point(field_get:cartographer.transform.proto.Vector2f.x)
  return _internal_x();
}
inline void Vector2f::_internal_set_x(float value) {
  
  x_ = value;
}
inline void Vector2f::set_x(float value) {
  _internal_set_x(value);
  // @@protoc_insertion_point(field_set:cartographer.transform.proto.Vector2f.x)
}

// float y = 2;
inline void Vector2f::clear_y() {
  y_ = 0;
}
inline float Vector2f::_internal_y() const {
  return y_;
}
inline float Vector2f::y() const {
  // @@protoc_insertion_point(field_get:cartographer.transform.proto.Vector2f.y)
  return _internal_y();
}
inline void Vector2f::_internal_set_y(float value) {
  
  y_ = value;
}
inline void Vector2f::set_y(float value) {
  _internal_set_y(value);
  // @@protoc_insertion_point(field_set:cartographer.transform.proto.Vector2f.y)
}

// -------------------------------------------------------------------

// Vector3d

// double x = 1;
inline void Vector3d::clear_x() {
  x_ = 0;
}
inline double Vector3d::_internal_x() const {
  return x_;
}
inline double Vector3d::x() const {
  // @@protoc_insertion_point(field_get:cartographer.transform.proto.Vector3d.x)
  return _internal_x();
}
inline void Vector3d::_internal_set_x(double value) {
  
  x_ = value;
}
inline void Vector3d::set_x(double value) {
  _internal_set_x(value);
  // @@protoc_insertion_point(field_set:cartographer.transform.proto.Vector3d.x)
}

// double y = 2;
inline void Vector3d::clear_y() {
  y_ = 0;
}
inline double Vector3d::_internal_y() const {
  return y_;
}
inline double Vector3d::y() const {
  // @@protoc_insertion_point(field_get:cartographer.transform.proto.Vector3d.y)
  return _internal_y();
}
inline void Vector3d::_internal_set_y(double value) {
  
  y_ = value;
}
inline void Vector3d::set_y(double value) {
  _internal_set_y(value);
  // @@protoc_insertion_point(field_set:cartographer.transform.proto.Vector3d.y)
}

// double z = 3;
inline void Vector3d::clear_z() {
  z_ = 0;
}
inline double Vector3d::_internal_z() const {
  return z_;
}
inline double Vector3d::z() const {
  // @@protoc_insertion_point(field_get:cartographer.transform.proto.Vector3d.z)
  return _internal_z();
}
inline void Vector3d::_internal_set_z(double value) {
  
  z_ = value;
}
inline void Vector3d::set_z(double value) {
  _internal_set_z(value);
  // @@protoc_insertion_point(field_set:cartographer.transform.proto.Vector3d.z)
}

// -------------------------------------------------------------------

// Vector3f

// float x = 1;
inline void Vector3f::clear_x() {
  x_ = 0;
}
inline float Vector3f::_internal_x() const {
  return x_;
}
inline float Vector3f::x() const {
  // @@protoc_insertion_point(field_get:cartographer.transform.proto.Vector3f.x)
  return _internal_x();
}
inline void Vector3f::_internal_set_x(float value) {
  
  x_ = value;
}
inline void Vector3f::set_x(float value) {
  _internal_set_x(value);
  // @@protoc_insertion_point(field_set:cartographer.transform.proto.Vector3f.x)
}

// float y = 2;
inline void Vector3f::clear_y() {
  y_ = 0;
}
inline float Vector3f::_internal_y() const {
  return y_;
}
inline float Vector3f::y() const {
  // @@protoc_insertion_point(field_get:cartographer.transform.proto.Vector3f.y)
  return _internal_y();
}
inline void Vector3f::_internal_set_y(float value) {
  
  y_ = value;
}
inline void Vector3f::set_y(float value) {
  _internal_set_y(value);
  // @@protoc_insertion_point(field_set:cartographer.transform.proto.Vector3f.y)
}

// float z = 3;
inline void Vector3f::clear_z() {
  z_ = 0;
}
inline float Vector3f::_internal_z() const {
  return z_;
}
inline float Vector3f::z() const {
  // @@protoc_insertion_point(field_get:cartographer.transform.proto.Vector3f.z)
  return _internal_z();
}
inline void Vector3f::_internal_set_z(float value) {
  
  z_ = value;
}
inline void Vector3f::set_z(float value) {
  _internal_set_z(value);
  // @@protoc_insertion_point(field_set:cartographer.transform.proto.Vector3f.z)
}

// -------------------------------------------------------------------

// Vector4f

// float x = 1;
inline void Vector4f::clear_x() {
  x_ = 0;
}
inline float Vector4f::_internal_x() const {
  return x_;
}
inline float Vector4f::x() const {
  // @@protoc_insertion_point(field_get:cartographer.transform.proto.Vector4f.x)
  return _internal_x();
}
inline void Vector4f::_internal_set_x(float value) {
  
  x_ = value;
}
inline void Vector4f::set_x(float value) {
  _internal_set_x(value);
  // @@protoc_insertion_point(field_set:cartographer.transform.proto.Vector4f.x)
}

// float y = 2;
inline void Vector4f::clear_y() {
  y_ = 0;
}
inline float Vector4f::_internal_y() const {
  return y_;
}
inline float Vector4f::y() const {
  // @@protoc_insertion_point(field_get:cartographer.transform.proto.Vector4f.y)
  return _internal_y();
}
inline void Vector4f::_internal_set_y(float value) {
  
  y_ = value;
}
inline void Vector4f::set_y(float value) {
  _internal_set_y(value);
  // @@protoc_insertion_point(field_set:cartographer.transform.proto.Vector4f.y)
}

// float z = 3;
inline void Vector4f::clear_z() {
  z_ = 0;
}
inline float Vector4f::_internal_z() const {
  return z_;
}
inline float Vector4f::z() const {
  // @@protoc_insertion_point(field_get:cartographer.transform.proto.Vector4f.z)
  return _internal_z();
}
inline void Vector4f::_internal_set_z(float value) {
  
  z_ = value;
}
inline void Vector4f::set_z(float value) {
  _internal_set_z(value);
  // @@protoc_insertion_point(field_set:cartographer.transform.proto.Vector4f.z)
}

// float t = 4;
inline void Vector4f::clear_t() {
  t_ = 0;
}
inline float Vector4f::_internal_t() const {
  return t_;
}
inline float Vector4f::t() const {
  // @@protoc_insertion_point(field_get:cartographer.transform.proto.Vector4f.t)
  return _internal_t();
}
inline void Vector4f::_internal_set_t(float value) {
  
  t_ = value;
}
inline void Vector4f::set_t(float value) {
  _internal_set_t(value);
  // @@protoc_insertion_point(field_set:cartographer.transform.proto.Vector4f.t)
}

// -------------------------------------------------------------------

// Quaterniond

// double x = 1;
inline void Quaterniond::clear_x() {
  x_ = 0;
}
inline double Quaterniond::_internal_x() const {
  return x_;
}
inline double Quaterniond::x() const {
  // @@protoc_insertion_point(field_get:cartographer.transform.proto.Quaterniond.x)
  return _internal_x();
}
inline void Quaterniond::_internal_set_x(double value) {
  
  x_ = value;
}
inline void Quaterniond::set_x(double value) {
  _internal_set_x(value);
  // @@protoc_insertion_point(field_set:cartographer.transform.proto.Quaterniond.x)
}

// double y = 2;
inline void Quaterniond::clear_y() {
  y_ = 0;
}
inline double Quaterniond::_internal_y() const {
  return y_;
}
inline double Quaterniond::y() const {
  // @@protoc_insertion_point(field_get:cartographer.transform.proto.Quaterniond.y)
  return _internal_y();
}
inline void Quaterniond::_internal_set_y(double value) {
  
  y_ = value;
}
inline void Quaterniond::set_y(double value) {
  _internal_set_y(value);
  // @@protoc_insertion_point(field_set:cartographer.transform.proto.Quaterniond.y)
}

// double z = 3;
inline void Quaterniond::clear_z() {
  z_ = 0;
}
inline double Quaterniond::_internal_z() const {
  return z_;
}
inline double Quaterniond::z() const {
  // @@protoc_insertion_point(field_get:cartographer.transform.proto.Quaterniond.z)
  return _internal_z();
}
inline void Quaterniond::_internal_set_z(double value) {
  
  z_ = value;
}
inline void Quaterniond::set_z(double value) {
  _internal_set_z(value);
  // @@protoc_insertion_point(field_set:cartographer.transform.proto.Quaterniond.z)
}

// double w = 4;
inline void Quaterniond::clear_w() {
  w_ = 0;
}
inline double Quaterniond::_internal_w() const {
  return w_;
}
inline double Quaterniond::w() const {
  // @@protoc_insertion_point(field_get:cartographer.transform.proto.Quaterniond.w)
  return _internal_w();
}
inline void Quaterniond::_internal_set_w(double value) {
  
  w_ = value;
}
inline void Quaterniond::set_w(double value) {
  _internal_set_w(value);
  // @@protoc_insertion_point(field_set:cartographer.transform.proto.Quaterniond.w)
}

// -------------------------------------------------------------------

// Quaternionf

// float x = 1;
inline void Quaternionf::clear_x() {
  x_ = 0;
}
inline float Quaternionf::_internal_x() const {
  return x_;
}
inline float Quaternionf::x() const {
  // @@protoc_insertion_point(field_get:cartographer.transform.proto.Quaternionf.x)
  return _internal_x();
}
inline void Quaternionf::_internal_set_x(float value) {
  
  x_ = value;
}
inline void Quaternionf::set_x(float value) {
  _internal_set_x(value);
  // @@protoc_insertion_point(field_set:cartographer.transform.proto.Quaternionf.x)
}

// float y = 2;
inline void Quaternionf::clear_y() {
  y_ = 0;
}
inline float Quaternionf::_internal_y() const {
  return y_;
}
inline float Quaternionf::y() const {
  // @@protoc_insertion_point(field_get:cartographer.transform.proto.Quaternionf.y)
  return _internal_y();
}
inline void Quaternionf::_internal_set_y(float value) {
  
  y_ = value;
}
inline void Quaternionf::set_y(float value) {
  _internal_set_y(value);
  // @@protoc_insertion_point(field_set:cartographer.transform.proto.Quaternionf.y)
}

// float z = 3;
inline void Quaternionf::clear_z() {
  z_ = 0;
}
inline float Quaternionf::_internal_z() const {
  return z_;
}
inline float Quaternionf::z() const {
  // @@protoc_insertion_point(field_get:cartographer.transform.proto.Quaternionf.z)
  return _internal_z();
}
inline void Quaternionf::_internal_set_z(float value) {
  
  z_ = value;
}
inline void Quaternionf::set_z(float value) {
  _internal_set_z(value);
  // @@protoc_insertion_point(field_set:cartographer.transform.proto.Quaternionf.z)
}

// float w = 4;
inline void Quaternionf::clear_w() {
  w_ = 0;
}
inline float Quaternionf::_internal_w() const {
  return w_;
}
inline float Quaternionf::w() const {
  // @@protoc_insertion_point(field_get:cartographer.transform.proto.Quaternionf.w)
  return _internal_w();
}
inline void Quaternionf::_internal_set_w(float value) {
  
  w_ = value;
}
inline void Quaternionf::set_w(float value) {
  _internal_set_w(value);
  // @@protoc_insertion_point(field_set:cartographer.transform.proto.Quaternionf.w)
}

// -------------------------------------------------------------------

// Rigid2d

// .cartographer.transform.proto.Vector2d translation = 1;
inline bool Rigid2d::_internal_has_translation() const {
  return this != internal_default_instance() && translation_ != nullptr;
}
inline bool Rigid2d::has_translation() const {
  return _internal_has_translation();
}
inline void Rigid2d::clear_translation() {
  if (GetArenaNoVirtual() == nullptr && translation_ != nullptr) {
    delete translation_;
  }
  translation_ = nullptr;
}
inline const ::cartographer::transform::proto::Vector2d& Rigid2d::_internal_translation() const {
  const ::cartographer::transform::proto::Vector2d* p = translation_;
  return p != nullptr ? *p : *reinterpret_cast<const ::cartographer::transform::proto::Vector2d*>(
      &::cartographer::transform::proto::_Vector2d_default_instance_);
}
inline const ::cartographer::transform::proto::Vector2d& Rigid2d::translation() const {
  // @@protoc_insertion_point(field_get:cartographer.transform.proto.Rigid2d.translation)
  return _internal_translation();
}
inline ::cartographer::transform::proto::Vector2d* Rigid2d::release_translation() {
  // @@protoc_insertion_point(field_release:cartographer.transform.proto.Rigid2d.translation)
  
  ::cartographer::transform::proto::Vector2d* temp = translation_;
  translation_ = nullptr;
  return temp;
}
inline ::cartographer::transform::proto::Vector2d* Rigid2d::_internal_mutable_translation() {
  
  if (translation_ == nullptr) {
    auto* p = CreateMaybeMessage<::cartographer::transform::proto::Vector2d>(GetArenaNoVirtual());
    translation_ = p;
  }
  return translation_;
}
inline ::cartographer::transform::proto::Vector2d* Rigid2d::mutable_translation() {
  // @@protoc_insertion_point(field_mutable:cartographer.transform.proto.Rigid2d.translation)
  return _internal_mutable_translation();
}
inline void Rigid2d::set_allocated_translation(::cartographer::transform::proto::Vector2d* translation) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == nullptr) {
    delete translation_;
  }
  if (translation) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena = nullptr;
    if (message_arena != submessage_arena) {
      translation = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, translation, submessage_arena);
    }
    
  } else {
    
  }
  translation_ = translation;
  // @@protoc_insertion_point(field_set_allocated:cartographer.transform.proto.Rigid2d.translation)
}

// double rotation = 2;
inline void Rigid2d::clear_rotation() {
  rotation_ = 0;
}
inline double Rigid2d::_internal_rotation() const {
  return rotation_;
}
inline double Rigid2d::rotation() const {
  // @@protoc_insertion_point(field_get:cartographer.transform.proto.Rigid2d.rotation)
  return _internal_rotation();
}
inline void Rigid2d::_internal_set_rotation(double value) {
  
  rotation_ = value;
}
inline void Rigid2d::set_rotation(double value) {
  _internal_set_rotation(value);
  // @@protoc_insertion_point(field_set:cartographer.transform.proto.Rigid2d.rotation)
}

// -------------------------------------------------------------------

// Rigid2f

// .cartographer.transform.proto.Vector2f translation = 1;
inline bool Rigid2f::_internal_has_translation() const {
  return this != internal_default_instance() && translation_ != nullptr;
}
inline bool Rigid2f::has_translation() const {
  return _internal_has_translation();
}
inline void Rigid2f::clear_translation() {
  if (GetArenaNoVirtual() == nullptr && translation_ != nullptr) {
    delete translation_;
  }
  translation_ = nullptr;
}
inline const ::cartographer::transform::proto::Vector2f& Rigid2f::_internal_translation() const {
  const ::cartographer::transform::proto::Vector2f* p = translation_;
  return p != nullptr ? *p : *reinterpret_cast<const ::cartographer::transform::proto::Vector2f*>(
      &::cartographer::transform::proto::_Vector2f_default_instance_);
}
inline const ::cartographer::transform::proto::Vector2f& Rigid2f::translation() const {
  // @@protoc_insertion_point(field_get:cartographer.transform.proto.Rigid2f.translation)
  return _internal_translation();
}
inline ::cartographer::transform::proto::Vector2f* Rigid2f::release_translation() {
  // @@protoc_insertion_point(field_release:cartographer.transform.proto.Rigid2f.translation)
  
  ::cartographer::transform::proto::Vector2f* temp = translation_;
  translation_ = nullptr;
  return temp;
}
inline ::cartographer::transform::proto::Vector2f* Rigid2f::_internal_mutable_translation() {
  
  if (translation_ == nullptr) {
    auto* p = CreateMaybeMessage<::cartographer::transform::proto::Vector2f>(GetArenaNoVirtual());
    translation_ = p;
  }
  return translation_;
}
inline ::cartographer::transform::proto::Vector2f* Rigid2f::mutable_translation() {
  // @@protoc_insertion_point(field_mutable:cartographer.transform.proto.Rigid2f.translation)
  return _internal_mutable_translation();
}
inline void Rigid2f::set_allocated_translation(::cartographer::transform::proto::Vector2f* translation) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == nullptr) {
    delete translation_;
  }
  if (translation) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena = nullptr;
    if (message_arena != submessage_arena) {
      translation = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, translation, submessage_arena);
    }
    
  } else {
    
  }
  translation_ = translation;
  // @@protoc_insertion_point(field_set_allocated:cartographer.transform.proto.Rigid2f.translation)
}

// float rotation = 2;
inline void Rigid2f::clear_rotation() {
  rotation_ = 0;
}
inline float Rigid2f::_internal_rotation() const {
  return rotation_;
}
inline float Rigid2f::rotation() const {
  // @@protoc_insertion_point(field_get:cartographer.transform.proto.Rigid2f.rotation)
  return _internal_rotation();
}
inline void Rigid2f::_internal_set_rotation(float value) {
  
  rotation_ = value;
}
inline void Rigid2f::set_rotation(float value) {
  _internal_set_rotation(value);
  // @@protoc_insertion_point(field_set:cartographer.transform.proto.Rigid2f.rotation)
}

// -------------------------------------------------------------------

// Rigid3d

// .cartographer.transform.proto.Vector3d translation = 1;
inline bool Rigid3d::_internal_has_translation() const {
  return this != internal_default_instance() && translation_ != nullptr;
}
inline bool Rigid3d::has_translation() const {
  return _internal_has_translation();
}
inline void Rigid3d::clear_translation() {
  if (GetArenaNoVirtual() == nullptr && translation_ != nullptr) {
    delete translation_;
  }
  translation_ = nullptr;
}
inline const ::cartographer::transform::proto::Vector3d& Rigid3d::_internal_translation() const {
  const ::cartographer::transform::proto::Vector3d* p = translation_;
  return p != nullptr ? *p : *reinterpret_cast<const ::cartographer::transform::proto::Vector3d*>(
      &::cartographer::transform::proto::_Vector3d_default_instance_);
}
inline const ::cartographer::transform::proto::Vector3d& Rigid3d::translation() const {
  // @@protoc_insertion_point(field_get:cartographer.transform.proto.Rigid3d.translation)
  return _internal_translation();
}
inline ::cartographer::transform::proto::Vector3d* Rigid3d::release_translation() {
  // @@protoc_insertion_point(field_release:cartographer.transform.proto.Rigid3d.translation)
  
  ::cartographer::transform::proto::Vector3d* temp = translation_;
  translation_ = nullptr;
  return temp;
}
inline ::cartographer::transform::proto::Vector3d* Rigid3d::_internal_mutable_translation() {
  
  if (translation_ == nullptr) {
    auto* p = CreateMaybeMessage<::cartographer::transform::proto::Vector3d>(GetArenaNoVirtual());
    translation_ = p;
  }
  return translation_;
}
inline ::cartographer::transform::proto::Vector3d* Rigid3d::mutable_translation() {
  // @@protoc_insertion_point(field_mutable:cartographer.transform.proto.Rigid3d.translation)
  return _internal_mutable_translation();
}
inline void Rigid3d::set_allocated_translation(::cartographer::transform::proto::Vector3d* translation) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == nullptr) {
    delete translation_;
  }
  if (translation) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena = nullptr;
    if (message_arena != submessage_arena) {
      translation = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, translation, submessage_arena);
    }
    
  } else {
    
  }
  translation_ = translation;
  // @@protoc_insertion_point(field_set_allocated:cartographer.transform.proto.Rigid3d.translation)
}

// .cartographer.transform.proto.Quaterniond rotation = 2;
inline bool Rigid3d::_internal_has_rotation() const {
  return this != internal_default_instance() && rotation_ != nullptr;
}
inline bool Rigid3d::has_rotation() const {
  return _internal_has_rotation();
}
inline void Rigid3d::clear_rotation() {
  if (GetArenaNoVirtual() == nullptr && rotation_ != nullptr) {
    delete rotation_;
  }
  rotation_ = nullptr;
}
inline const ::cartographer::transform::proto::Quaterniond& Rigid3d::_internal_rotation() const {
  const ::cartographer::transform::proto::Quaterniond* p = rotation_;
  return p != nullptr ? *p : *reinterpret_cast<const ::cartographer::transform::proto::Quaterniond*>(
      &::cartographer::transform::proto::_Quaterniond_default_instance_);
}
inline const ::cartographer::transform::proto::Quaterniond& Rigid3d::rotation() const {
  // @@protoc_insertion_point(field_get:cartographer.transform.proto.Rigid3d.rotation)
  return _internal_rotation();
}
inline ::cartographer::transform::proto::Quaterniond* Rigid3d::release_rotation() {
  // @@protoc_insertion_point(field_release:cartographer.transform.proto.Rigid3d.rotation)
  
  ::cartographer::transform::proto::Quaterniond* temp = rotation_;
  rotation_ = nullptr;
  return temp;
}
inline ::cartographer::transform::proto::Quaterniond* Rigid3d::_internal_mutable_rotation() {
  
  if (rotation_ == nullptr) {
    auto* p = CreateMaybeMessage<::cartographer::transform::proto::Quaterniond>(GetArenaNoVirtual());
    rotation_ = p;
  }
  return rotation_;
}
inline ::cartographer::transform::proto::Quaterniond* Rigid3d::mutable_rotation() {
  // @@protoc_insertion_point(field_mutable:cartographer.transform.proto.Rigid3d.rotation)
  return _internal_mutable_rotation();
}
inline void Rigid3d::set_allocated_rotation(::cartographer::transform::proto::Quaterniond* rotation) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == nullptr) {
    delete rotation_;
  }
  if (rotation) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena = nullptr;
    if (message_arena != submessage_arena) {
      rotation = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, rotation, submessage_arena);
    }
    
  } else {
    
  }
  rotation_ = rotation;
  // @@protoc_insertion_point(field_set_allocated:cartographer.transform.proto.Rigid3d.rotation)
}

// -------------------------------------------------------------------

// Rigid3f

// .cartographer.transform.proto.Vector3f translation = 1;
inline bool Rigid3f::_internal_has_translation() const {
  return this != internal_default_instance() && translation_ != nullptr;
}
inline bool Rigid3f::has_translation() const {
  return _internal_has_translation();
}
inline void Rigid3f::clear_translation() {
  if (GetArenaNoVirtual() == nullptr && translation_ != nullptr) {
    delete translation_;
  }
  translation_ = nullptr;
}
inline const ::cartographer::transform::proto::Vector3f& Rigid3f::_internal_translation() const {
  const ::cartographer::transform::proto::Vector3f* p = translation_;
  return p != nullptr ? *p : *reinterpret_cast<const ::cartographer::transform::proto::Vector3f*>(
      &::cartographer::transform::proto::_Vector3f_default_instance_);
}
inline const ::cartographer::transform::proto::Vector3f& Rigid3f::translation() const {
  // @@protoc_insertion_point(field_get:cartographer.transform.proto.Rigid3f.translation)
  return _internal_translation();
}
inline ::cartographer::transform::proto::Vector3f* Rigid3f::release_translation() {
  // @@protoc_insertion_point(field_release:cartographer.transform.proto.Rigid3f.translation)
  
  ::cartographer::transform::proto::Vector3f* temp = translation_;
  translation_ = nullptr;
  return temp;
}
inline ::cartographer::transform::proto::Vector3f* Rigid3f::_internal_mutable_translation() {
  
  if (translation_ == nullptr) {
    auto* p = CreateMaybeMessage<::cartographer::transform::proto::Vector3f>(GetArenaNoVirtual());
    translation_ = p;
  }
  return translation_;
}
inline ::cartographer::transform::proto::Vector3f* Rigid3f::mutable_translation() {
  // @@protoc_insertion_point(field_mutable:cartographer.transform.proto.Rigid3f.translation)
  return _internal_mutable_translation();
}
inline void Rigid3f::set_allocated_translation(::cartographer::transform::proto::Vector3f* translation) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == nullptr) {
    delete translation_;
  }
  if (translation) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena = nullptr;
    if (message_arena != submessage_arena) {
      translation = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, translation, submessage_arena);
    }
    
  } else {
    
  }
  translation_ = translation;
  // @@protoc_insertion_point(field_set_allocated:cartographer.transform.proto.Rigid3f.translation)
}

// .cartographer.transform.proto.Quaternionf rotation = 2;
inline bool Rigid3f::_internal_has_rotation() const {
  return this != internal_default_instance() && rotation_ != nullptr;
}
inline bool Rigid3f::has_rotation() const {
  return _internal_has_rotation();
}
inline void Rigid3f::clear_rotation() {
  if (GetArenaNoVirtual() == nullptr && rotation_ != nullptr) {
    delete rotation_;
  }
  rotation_ = nullptr;
}
inline const ::cartographer::transform::proto::Quaternionf& Rigid3f::_internal_rotation() const {
  const ::cartographer::transform::proto::Quaternionf* p = rotation_;
  return p != nullptr ? *p : *reinterpret_cast<const ::cartographer::transform::proto::Quaternionf*>(
      &::cartographer::transform::proto::_Quaternionf_default_instance_);
}
inline const ::cartographer::transform::proto::Quaternionf& Rigid3f::rotation() const {
  // @@protoc_insertion_point(field_get:cartographer.transform.proto.Rigid3f.rotation)
  return _internal_rotation();
}
inline ::cartographer::transform::proto::Quaternionf* Rigid3f::release_rotation() {
  // @@protoc_insertion_point(field_release:cartographer.transform.proto.Rigid3f.rotation)
  
  ::cartographer::transform::proto::Quaternionf* temp = rotation_;
  rotation_ = nullptr;
  return temp;
}
inline ::cartographer::transform::proto::Quaternionf* Rigid3f::_internal_mutable_rotation() {
  
  if (rotation_ == nullptr) {
    auto* p = CreateMaybeMessage<::cartographer::transform::proto::Quaternionf>(GetArenaNoVirtual());
    rotation_ = p;
  }
  return rotation_;
}
inline ::cartographer::transform::proto::Quaternionf* Rigid3f::mutable_rotation() {
  // @@protoc_insertion_point(field_mutable:cartographer.transform.proto.Rigid3f.rotation)
  return _internal_mutable_rotation();
}
inline void Rigid3f::set_allocated_rotation(::cartographer::transform::proto::Quaternionf* rotation) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == nullptr) {
    delete rotation_;
  }
  if (rotation) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena = nullptr;
    if (message_arena != submessage_arena) {
      rotation = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, rotation, submessage_arena);
    }
    
  } else {
    
  }
  rotation_ = rotation;
  // @@protoc_insertion_point(field_set_allocated:cartographer.transform.proto.Rigid3f.rotation)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace proto
}  // namespace transform
}  // namespace cartographer

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_cartographer_2ftransform_2fproto_2ftransform_2eproto
